version: '3.8'

services:
  backend:
    image: ghcr.io/veucci/project-ybs410-backend:latest
    container_name: project-ybs410-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ai:/app/ai # Mount AI model directory
      - ./backend/uploads:/app/uploads # Mount uploads directory
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    image: ghcr.io/veucci/project-ybs410-frontend:latest
    container_name: project-ybs410-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000 # Backend API URL
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: ybs410-network
    driver: bridge
